### ISSUE TITLE
nice try :)

### ISSUE THREAD

**Issue by optixyt0** [MarvelcoOGFN/luna-launcher#1]
you got the wrong launcher, it's just a template project made by Akadi that you uploaded. @MarvelcoOGFN You seriously think that you are cool by 'leaking' (you've failed this time), people's code. Get a life.

**Comment by optixyt0** [comment]
Why did you become like this bro. You 'expose' people for skidding, while you literally skid EonGS and Lawin.

**Comment by optixyt0** [comment]
You used to be nice.

**Comment by endlessalpacaYT** [comment]
less brainless than you are
