### ISSUE TITLE
Lmao

### ISSUE THREAD

**Issue by Akadi5** [MarvelcoOGFN/luna-launcher#2]
You good? Thats not even the right launcher.

**Comment by optixyt0** [comment]
fr

**Comment by optixyt0** [comment]
@MarvelcoOGFN imagine not being able to tell that i couldnt be bothered to push the launcher, and posting a literal template.

**Comment by MarvelcoOGFN** [comment]
@optixyt0 @Akadi5 idc if its a template lmao also bro if you didn't care then you wouldn't have opened issues saying that also bro @Akadi5 the so called api you added to the backend is litterly skidded from flipped and most of your shit is made by chat gpt including this launcher so fuck both of you

**Comment by Akadi5** [comment]
Thats very childish from you
